<?xml version="1.0"?>
<robot name="girona500" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
<!--  <xacro:include filename="$(find gtri_based_sonar_gazebo)/urdf/robot.gazebo" /> -->
  <xacro:include filename="$(find gtri_based_sonar_gazebo)/urdf/robot.xacro" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find g500arm5_description)/urdf/materials.xacro" />

  <link name="base_link">
    <visual>
      <origin rpy="1.57079 0 3.1416" xyz="0 0 0"/>
      <geometry>
        <cylinder length="1.5" radius="0.35"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="1.5" radius="0.35"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="98"/>
      <inertia ixx="8.0" ixy="0.0" ixz="0.0" 
                         iyy="8.0" iyz="0.0" 
                                   izz="8.0"/>
    </inertial>          
  </link>

  <!-- SONAR HORIZONTAL -->
  <xacro:property name="sonar_length" value="0.15" />
  <xacro:property name="sonar_radius" value="0.05" />
  <joint name="sonar_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="0.70 0 0" rpy="0 ${pi} ${pi}"/>
    <!--<origin xyz="${sonar_length/2} 0 0" rpy="${-pi/2} ${pi} ${pi}"/>-->
    <parent link="base_link"/>
    <child link="sonar_link"/>
  </joint>
  
  <link name="sonar_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>      
      <geometry>
        <cylinder length="${sonar_length}" radius="${sonar_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="${sonar_length}" radius="${sonar_radius}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- SONAR VERTICAL -->
  <xacro:property name="sonar_length" value="0.15" />
  <xacro:property name="sonar_radius" value="0.05" />
  <joint name="sonar_joint_vertical" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="0.70 0 0" rpy="${-pi/2} ${pi} ${pi}"/>
    <!--<origin xyz="${sonar_length/2} 0 0" rpy="${-pi/2} ${pi} ${pi}"/>-->
    <parent link="base_link"/>
    <child link="sonar_vertical_link"/>
  </joint>
  
  <link name="sonar_vertical_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>      
      <geometry>
        <cylinder length="${sonar_length}" radius="${sonar_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="${sonar_length}" radius="${sonar_radius}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- Camera -->
  <xacro:property name="camera_size" value="0.05" />
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 0 1.5708" />
    <origin xyz="0.725 0 0.2" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

</robot>

